version: '3.8'
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
  celery_worker:
    build: .
    container_name: celery_worker
    command: sh run_celery.sh
    depends_on:
      - redis
    volumes:
      - ./:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
